<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-AnkiLingo-eb05c2d2-46b7-4dbf-aef9-fb8371fcdbbd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise" Version="1.8.9" />
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.8.9" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.8.9" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.21" />
  </ItemGroup>

</Project>
